apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadbzeo6630-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadbzeo6630-tenant-component
    app.kubernetes.io/part-of: loadbzeo6630-tenant-app
  name: loadbzeo6630-tenant-component
  namespace: loadbzeo6630-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadbzeo6630-tenant-component
    weight: null
status: {}
